version: '3'

services:

  frontend:
    build:
      context: .
      dockerfile: ./compose/production/Dockerfile
    image: mt2web-frontend
    ports:
      - 8001:4000
    networks: 
      - my-proxy-net

networks:
  my-proxy-net:
    external:
      name: custom_network
